// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ClientProtocol.proto

package siodb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//* Command from client to server.
type Command struct {
	//* Request ID
	RequestID uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	//* Command text
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8258ee83f8f443, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetRequestID() uint64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *Command) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

//* Response from server.
type ServerResponse struct {
	//* Corresponding request ID.
	RequestID uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	//* Messages from server.
	Message []*StatusMessage `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
	//* Description of columns in this data set.
	ColumnDescription []*ColumnDescription `protobuf:"bytes,3,rep,name=column_description,json=columnDescription,proto3" json:"column_description,omitempty"`
	//* Free text messages without status code.
	FreetextMessage []string `protobuf:"bytes,4,rep,name=freetext_message,json=freetextMessage,proto3" json:"freetext_message,omitempty"`
	//* Number of this response in series of responses. Starts with 0.
	ResponseId uint32 `protobuf:"varint,5,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	//*
	// Number of reponses in series.
	// May be sent only in first response.
	// Zero value means single response.
	ResponseCount uint32 `protobuf:"varint,6,opt,name=response_count,json=responseCount,proto3" json:"response_count,omitempty"`
	//* Indicates that affected row count is presents.
	HasAffectedRowCount bool `protobuf:"varint,7,opt,name=has_affected_row_count,json=hasAffectedRowCount,proto3" json:"has_affected_row_count,omitempty"`
	//* Affected row count.
	AffectedRowCount     uint64   `protobuf:"varint,8,opt,name=affected_row_count,json=affectedRowCount,proto3" json:"affected_row_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8258ee83f8f443, []int{1}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetRequestID() uint64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *ServerResponse) GetMessage() []*StatusMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ServerResponse) GetColumnDescription() []*ColumnDescription {
	if m != nil {
		return m.ColumnDescription
	}
	return nil
}

func (m *ServerResponse) GetFreetextMessage() []string {
	if m != nil {
		return m.FreetextMessage
	}
	return nil
}

func (m *ServerResponse) GetResponseId() uint32 {
	if m != nil {
		return m.ResponseId
	}
	return 0
}

func (m *ServerResponse) GetResponseCount() uint32 {
	if m != nil {
		return m.ResponseCount
	}
	return 0
}

func (m *ServerResponse) GetHasAffectedRowCount() bool {
	if m != nil {
		return m.HasAffectedRowCount
	}
	return false
}

func (m *ServerResponse) GetAffectedRowCount() uint64 {
	if m != nil {
		return m.AffectedRowCount
	}
	return 0
}

//* Begin session request
type BeginSessionRequest struct {
	//* User name
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginSessionRequest) Reset()         { *m = BeginSessionRequest{} }
func (m *BeginSessionRequest) String() string { return proto.CompactTextString(m) }
func (*BeginSessionRequest) ProtoMessage()    {}
func (*BeginSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8258ee83f8f443, []int{2}
}

func (m *BeginSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginSessionRequest.Unmarshal(m, b)
}
func (m *BeginSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginSessionRequest.Marshal(b, m, deterministic)
}
func (m *BeginSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginSessionRequest.Merge(m, src)
}
func (m *BeginSessionRequest) XXX_Size() int {
	return xxx_messageInfo_BeginSessionRequest.Size(m)
}
func (m *BeginSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginSessionRequest proto.InternalMessageInfo

func (m *BeginSessionRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

//* Begin session response.
type BeginSessionResponse struct {
	//* Indication that session is started.
	SessionStarted bool `protobuf:"varint,1,opt,name=session_started,json=sessionStarted,proto3" json:"session_started,omitempty"`
	//* Message from IO manager. Set in case of error(session_started = false).
	Message *StatusMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	//* Challenge. Sent only in case if session is started.
	Challenge            []byte   `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginSessionResponse) Reset()         { *m = BeginSessionResponse{} }
func (m *BeginSessionResponse) String() string { return proto.CompactTextString(m) }
func (*BeginSessionResponse) ProtoMessage()    {}
func (*BeginSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8258ee83f8f443, []int{3}
}

func (m *BeginSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginSessionResponse.Unmarshal(m, b)
}
func (m *BeginSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginSessionResponse.Marshal(b, m, deterministic)
}
func (m *BeginSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginSessionResponse.Merge(m, src)
}
func (m *BeginSessionResponse) XXX_Size() int {
	return xxx_messageInfo_BeginSessionResponse.Size(m)
}
func (m *BeginSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeginSessionResponse proto.InternalMessageInfo

func (m *BeginSessionResponse) GetSessionStarted() bool {
	if m != nil {
		return m.SessionStarted
	}
	return false
}

func (m *BeginSessionResponse) GetMessage() *StatusMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *BeginSessionResponse) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

//* User authentication request.
type ClientAuthenticationRequest struct {
	//* User message signature.
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientAuthenticationRequest) Reset()         { *m = ClientAuthenticationRequest{} }
func (m *ClientAuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*ClientAuthenticationRequest) ProtoMessage()    {}
func (*ClientAuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8258ee83f8f443, []int{4}
}

func (m *ClientAuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientAuthenticationRequest.Unmarshal(m, b)
}
func (m *ClientAuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientAuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *ClientAuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientAuthenticationRequest.Merge(m, src)
}
func (m *ClientAuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_ClientAuthenticationRequest.Size(m)
}
func (m *ClientAuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientAuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientAuthenticationRequest proto.InternalMessageInfo

func (m *ClientAuthenticationRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

//* User authentication response.
type ClientAuthenticationResponse struct {
	//* Indication that user is authenticated.
	Authenticated bool `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	//* Message from IO manager. Set in case of error.
	Message *StatusMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	//* ID of started session.
	SessionId            string   `protobuf:"bytes,3,opt,name=session_id,json=sessionID,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientAuthenticationResponse) Reset()         { *m = ClientAuthenticationResponse{} }
func (m *ClientAuthenticationResponse) String() string { return proto.CompactTextString(m) }
func (*ClientAuthenticationResponse) ProtoMessage()    {}
func (*ClientAuthenticationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8258ee83f8f443, []int{5}
}

func (m *ClientAuthenticationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientAuthenticationResponse.Unmarshal(m, b)
}
func (m *ClientAuthenticationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientAuthenticationResponse.Marshal(b, m, deterministic)
}
func (m *ClientAuthenticationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientAuthenticationResponse.Merge(m, src)
}
func (m *ClientAuthenticationResponse) XXX_Size() int {
	return xxx_messageInfo_ClientAuthenticationResponse.Size(m)
}
func (m *ClientAuthenticationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientAuthenticationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientAuthenticationResponse proto.InternalMessageInfo

func (m *ClientAuthenticationResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *ClientAuthenticationResponse) GetMessage() *StatusMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ClientAuthenticationResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "siodb.client_protocol.Command")
	proto.RegisterType((*ServerResponse)(nil), "siodb.client_protocol.ServerResponse")
	proto.RegisterType((*BeginSessionRequest)(nil), "siodb.client_protocol.BeginSessionRequest")
	proto.RegisterType((*BeginSessionResponse)(nil), "siodb.client_protocol.BeginSessionResponse")
	proto.RegisterType((*ClientAuthenticationRequest)(nil), "siodb.client_protocol.ClientAuthenticationRequest")
	proto.RegisterType((*ClientAuthenticationResponse)(nil), "siodb.client_protocol.ClientAuthenticationResponse")
}

func init() { proto.RegisterFile("ClientProtocol.proto", fileDescriptor_6a8258ee83f8f443) }

var fileDescriptor_6a8258ee83f8f443 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0xe5, 0xb6, 0xac, 0xcd, 0xdb, 0xda, 0x6d, 0x5e, 0x41, 0x11, 0xeb, 0x44, 0x14, 0x81,
	0x08, 0x12, 0xea, 0x61, 0x3b, 0xc2, 0x65, 0x2b, 0x12, 0xf4, 0x00, 0x42, 0x2e, 0xf7, 0xc8, 0x4b,
	0x5e, 0xdb, 0x48, 0x8d, 0x1d, 0x6c, 0x87, 0xc1, 0x1f, 0xc1, 0x89, 0xff, 0x17, 0xa1, 0xd8, 0xce,
	0x4a, 0xa7, 0x49, 0xd3, 0x6e, 0xd6, 0xef, 0xfb, 0xbe, 0xc4, 0xdf, 0x7b, 0x09, 0x8c, 0x67, 0x9b,
	0x02, 0x85, 0xf9, 0xaa, 0xa4, 0x91, 0x99, 0xdc, 0x4c, 0xab, 0xe6, 0x40, 0x9f, 0xea, 0x42, 0xe6,
	0xd7, 0xd3, 0xcc, 0x6a, 0x69, 0xe5, 0xc5, 0xe7, 0xc7, 0x33, 0x59, 0x96, 0x52, 0x7c, 0xfb, 0x55,
	0xa1, 0x76, 0xce, 0xf8, 0x3d, 0xf4, 0x1b, 0xc8, 0x45, 0x4e, 0xcf, 0x00, 0x14, 0x7e, 0xaf, 0x51,
	0x9b, 0xb4, 0xc8, 0x43, 0x12, 0x91, 0xa4, 0xc7, 0x02, 0x4f, 0xe6, 0x39, 0xa5, 0xd0, 0x33, 0xf8,
	0xd3, 0x84, 0x9d, 0x88, 0x24, 0x01, 0xb3, 0xe7, 0xf8, 0x6f, 0x07, 0x46, 0x0b, 0x54, 0x3f, 0x50,
	0x31, 0xd4, 0x95, 0x14, 0x1a, 0x1f, 0x7a, 0xca, 0x14, 0xfa, 0x25, 0x6a, 0xcd, 0x57, 0x18, 0x76,
	0xa2, 0x6e, 0xb2, 0x7f, 0x3e, 0x9e, 0xba, 0xbb, 0x2e, 0x0c, 0x37, 0xb5, 0xfe, 0xec, 0x34, 0xd6,
	0x9a, 0xe8, 0x47, 0xa0, 0x99, 0xdc, 0xd4, 0xa5, 0x48, 0x73, 0xd4, 0x99, 0x2a, 0x2a, 0x53, 0x48,
	0x11, 0x76, 0x6d, 0x34, 0xf4, 0xd1, 0x99, 0x35, 0x7c, 0xd8, 0xea, 0xec, 0x38, 0xbb, 0x8b, 0xe8,
	0x1b, 0x38, 0x5a, 0x2a, 0xc4, 0xe6, 0xda, 0x69, 0x7b, 0x83, 0x5e, 0xd4, 0x4d, 0x02, 0x76, 0xd8,
	0x72, 0xff, 0x72, 0xfa, 0x02, 0xf6, 0x95, 0xaf, 0xd3, 0x74, 0x78, 0x12, 0x91, 0x64, 0xc8, 0xa0,
	0x45, 0xf3, 0x9c, 0xbe, 0x82, 0xd1, 0xad, 0x21, 0x93, 0xb5, 0x30, 0xe1, 0x9e, 0xf5, 0x0c, 0x5b,
	0x3a, 0x6b, 0x20, 0xbd, 0x80, 0x67, 0x6b, 0xae, 0x53, 0xbe, 0x5c, 0x62, 0x66, 0x30, 0x4f, 0x95,
	0xbc, 0xf1, 0xf6, 0x7e, 0x44, 0x92, 0x01, 0x3b, 0x59, 0x73, 0x7d, 0xe9, 0x45, 0x26, 0x6f, 0x5c,
	0xe8, 0x2d, 0xd0, 0x7b, 0x02, 0x03, 0x3b, 0xc7, 0x23, 0x7e, 0xc7, 0x1d, 0x9f, 0xc3, 0xc9, 0x15,
	0xae, 0x0a, 0xb1, 0x40, 0xad, 0x9b, 0xe2, 0x6e, 0xce, 0xf4, 0x14, 0x82, 0x5a, 0xa3, 0x4a, 0x05,
	0x2f, 0xd1, 0xee, 0x20, 0x60, 0x83, 0x06, 0x7c, 0xe1, 0x25, 0xc6, 0xbf, 0x09, 0x8c, 0x77, 0x43,
	0x7e, 0x75, 0xaf, 0xe1, 0x50, 0x3b, 0x94, 0x6a, 0xc3, 0x95, 0x41, 0xb7, 0xbf, 0x01, 0x1b, 0x79,
	0xbc, 0x70, 0x74, 0x77, 0x89, 0xe4, 0xe1, 0x25, 0x4e, 0x20, 0xc8, 0xd6, 0x7c, 0xb3, 0x41, 0xb1,
	0xc2, 0xb0, 0x1b, 0x91, 0xe4, 0x80, 0x6d, 0x41, 0xfc, 0x0e, 0x4e, 0xdd, 0x47, 0x7c, 0x59, 0x9b,
	0x35, 0x0a, 0x53, 0x64, 0xdc, 0xfc, 0xd7, 0x65, 0x02, 0x81, 0x2e, 0x56, 0x82, 0x9b, 0x5a, 0xb9,
	0x2e, 0x07, 0x6c, 0x0b, 0xe2, 0x3f, 0x04, 0x26, 0xf7, 0xa7, 0x7d, 0xa9, 0x97, 0x30, 0xe4, 0x5b,
	0xe5, 0xb6, 0xd2, 0x2e, 0x7c, 0x74, 0xa3, 0x33, 0x80, 0x76, 0x54, 0x45, 0x6e, 0x2b, 0x05, 0x2c,
	0xf0, 0x64, 0x9e, 0x5f, 0x75, 0x3e, 0x91, 0xeb, 0x3d, 0xfb, 0x83, 0x5d, 0xfc, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x6b, 0x80, 0xb9, 0x96, 0xa2, 0x03, 0x00, 0x00,
}
